### ISSUE TITLE
Redesign Engines and APIs for C++17

### ISSUE THREAD

**Issue by mogemimi** [mogemimi/pomdog#14]
Hello, mates!
I have the following plans for Pomdog in 2018:

### Plans

- To migrate C++14 -> C++17 (or C++1z), I will remove support for such old compilers and IDEs:
  - Visual Studio < 2017
  - Xcode < 9.2
  - LLVM Clang < 5.0
- Migrating a new build system from GYP
- Removing all tools written by Python 2.x from our toolchains
- Using [Catch2](https://github.com/catchorg/Catch2) as a test framework 
- Update the version of clang-format and `.clang-format`
- Upgrading third-party libraries, docker containers and CI settings.

### New API Style

- **Use C++17, not C++14**
- Replacing `Pomdog::Optional<T>`, `Pomdog::Any` and `Pomdog::PathHelper` with the C++17 standard libraries.
- Do not use Exceptions in favor of the `std::tuple`, `std::tie` and `std::optional` for error handling.
- More documentations and examples.

**Comment by mogemimi** [comment]
### Progress

- [x] [Ubuntu docker container for CI](https://github.com/mogemimi/ubuntu-gamedev-docker)
  - Clang: 3.8 -> 5.0
  - Ubuntu: 17.04 -> 17.10
- [x] Wercker CI: Clang 3.8 -> 5.0, C++14 -> C++17
- [x] Travis CI settings
  - Xcode: 8.3 -> 9.2

### TODO

- [ ] [Fix some build errors with Clang 5.0 on a new Ubuntu ](https://app.wercker.com/mogemimi/pomdog/runs/build/5a6a734d34645f00019b4d7a?step=5a6a73586467270001f62a68)
- Updating third-party libraries
  - [ ] zlib
  - [ ] libpng
  - [ ] rapidjson

**Comment by mogemimi** [comment]
Hello @barsoosayque,

> this part can also be refactored in favor of c++17 std

I agree with you. These APIs will be replaced with `<file_system>` and will be deprecated. 👍 
Currently, Mac (Xcode 9) does not support `<file_system>`  and `<experimental/file_system>` yet, so I'll upgrade the build requirements of Pomdog for the C++17 libraries when Xcode 10 stable will be released.

`GetResourceDirectoryPath()` represents a asset directory which includes the `Content` directory. When you build the application, the `Content` directory is copied into it from your source directory. It is usually the same as where the executable file is located.

`GetLocalAppDataDirectoryPath()` and `GetAppDataDirectoryPath()` are equal to `/home/<Username>/.<application-name>/`, like `~/.thunderbird` or `~/.minecraft` on Linux, but these are not been implemented yet, please see [FileSystemLinux.cpp#L70-L80](https://github.com/mogemimi/pomdog/blob/v0.1.3/src/Platform.Linux/FileSystemLinux.cpp#L70-L80).

In addition, these are platform-specific APIs which is causing confusion, so I'd like to change them as follows:

```cpp
// current version
std::string GetLocalAppDataDirectoryPath();
std::string GetAppDataDirectoryPath();

// next version (TBD)
std::optional<std::string> Win32::GetLocalAppDataDirectoryPath();
std::optional<std::string> Win32::GetAppDataDirectoryPath();
std::optional<std::string> Mac::GetApplicationSupportDirectoryPath();
std::optional<std::string> Linux::GetHomeDirectoryPath();
std::string GetContentDirectoryPath();
std::string GetPersistentDataDirectoryPath();
```

**Comment by barsoosayque** [comment]
> ... are equal to `/home/<Username>/.<application-name>/`, like `~/.thunderbird` or `~/.minecraft` on Linux.

It is now desirable to store game data (or any other program specific data, but not the configs) in `$HOME/.local/share/<application-name>/` according to the [XDG Specification][1].

Regarding next filesystem API, I guess it will be more convenient to return `std::filesystem::path` and then do `path.c_str()` or `path.string()`.

[1]: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by mogemimi** [comment]
> ... $HOME/.local/share/<application-name>/ according to the XDG Specification.

Thank you for the link. That seems like the right path! I'll read the spec and try it.

> it will be more convenient to return `std::filesystem::path`

I totally agree with this direction. 👍
